# Generated by Django 4.2 on 2025-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Уникальный текст цитаты",
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Откуда цитата: фильм, книга и т.д.",
                        max_length=200,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Чем выше, тем чаще будет показываться",
                    ),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, help_text="Лайки"
                    ),
                ),
                (
                    "dislikes",
                    models.PositiveIntegerField(
                        default=0, help_text="Дизлайки"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество просмотров",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
                "ordering": ["-likes", "-views", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["source"],
                name="quotes_quot_source_3cbf0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["-likes"],
                name="quotes_quot_likes_2f7ea6_idx",
            ),
        ),
    ]
