# Generated by Django 4.2 on 2025-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="source",
            field=models.CharField(
                help_text="Источник цитаты", max_length=200
            ),
        ),
    ]
