# Generated by Django 4.2 on 2025-08-26 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_quote_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="source",
            field=models.CharField(
                help_text="Источник цитаты",
                max_length=200,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=models.TextField(
                help_text="Уникальный текст цитаты",
                unique=True,
                verbose_name="Текст цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="weight",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Чем больше вес, тем чаще цитата будет выпадать (от 1 до 7)",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Вес не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        7, "Вес не может быть больше 7"
                    ),
                ],
                verbose_name="Вес цитаты",
            ),
        ),
    ]
